### ISSUE TITLE
Example don't work : eID service shutdown

### ISSUE THREAD

**Issue by Levure** [e-Contract/eid-idp-php-example#1]
The provided example does not work, it displays the following error : 

> eID Identity Provider
> eID Authentication
> 
> The web application has requested an eID authentication operation.
> 
> WARNING: this eID service has been shut down
> Please inform the administrators of the web application, in which you try to log in, about the shut
> down of this eID service. Administrators can then take contact with us for the transition towards the
> new and improved eID service of e-Contract.be BVBA.

**Comment by david-vde** [comment]
Same for me these examples does not works.
I don't understand why it is so difficult to find an up to date documentation with correct simple examples for eid identification. It's time consuming:

eID Identity Provider

Error

An error occurred.

Error timestamp:    Wed May 25 08:48:40 CEST 2016
Error identifier:   a5967b70-5032-4b58-b775-318ac6cbcdd6

**Comment by fcorneli** [comment]
Try to change the "localhost" value within
`$openid = new LightOpenID('localhost');`
with the actual DNS name that you're using.

**Comment by david-vde** [comment]
Thank you very much it solved the problem.
